---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
- name: web-ui
- name: web-version

outputs:
- name: build

params:
  TERM: dumb

run:
  path: web-ui/ci/build.sh
